/**
 * This file is part of Totara Enterprise Extensions.
 *
 * Copyright (C) 2020 onwards Totara Learning Solutions LTD
 *
 * Totara Enterprise Extensions is provided only to Totara
 * Learning Solutions LTD's customers and partners, pursuant to
 * the terms and conditions of a separate agreement with Totara
 * Learning Solutions LTD or its affiliate.
 *
 * If you do not have an agreement with Totara Learning Solutions
 * LTD, you may not access, use, modify, or distribute this software.
 * Please contact [licensing@totaralearning.com] for more information.
 *
 * @author Simon Chester <simon.chester@totaralearning.com>
 * @module editor_weka
 */

import tui from 'tui/tui';
import { throttle } from 'tui/util';
import Weka from 'editor_weka/components/Weka';
import WekaValue from './WekaValue';
import { getDefaultDocument } from './helpers/editor';

/**
 * Set up Weka editor on element generated by core editor code.
 *
 * @param {object} options
 * @param {string} options.id             ID of textarea in DOM
 * @param {object[]} options.extensions
 * @param {boolean} options.showtoolbar
 * @param {number} options.file_item_id   The file draft's item id.
 * @param {number} options.context_id     The context's id.
 */
export function setupTextarea({
  id,
  extensions,
  showtoolbar,
  file_item_id,
  context_id,
}) {
  const el = document.getElementById(id);
  if (!el) {
    const error = new Error('Textarea not found');
    error.code = 'TEXTAREA_NOT_FOUND';
    throw error;
  }

  const options = {
    extensions,
    showtoolbar,
    context_id,
    file_item_id: file_item_id,
  };

  new IntegrationView(id, el, options);
}

class IntegrationView {
  constructor(id, textareaEl, editorOptions) {
    this.id = id;
    this.textareaEl = textareaEl;
    textareaEl.style.display = 'none';
    textareaEl.setAttribute('data-enhanced', true);

    this.wrapper = document.createElement('div');
    const el = document.createElement('div');
    this.wrapper.appendChild(el);

    this.textareaEl.parentNode.insertBefore(
      this.wrapper,
      this.textareaEl.nextSibling
    );

    let initialValue = this.getWekaValue();

    this.wekaValue = null;

    const update = () => {
      if (this.wekaValue) {
        this.textareaEl.value = JSON.stringify(this.wekaValue.getDoc());
        this.textareaEl.dispatchEvent(new Event('change', { bubbles: true }));
      }
    };
    const throttledUpdate = throttle(update, 250);

    tui.mount(
      Weka,
      {
        props: {
          value: initialValue,
          options: editorOptions,
          fileItemId: editorOptions.file_item_id
            ? editorOptions.file_item_id
            : undefined,
        },
        on: {
          input: value => {
            this.wekaValue = value;
            throttledUpdate();
          },
          blur: update,
        },
      },
      el
    );
  }

  /**
   * Get document from textarea
   *
   * @returns object
   */
  getWekaValue() {
    let doc = getDefaultDocument();

    let rawVal = this.textareaEl.value;

    if (rawVal) {
      try {
        doc = JSON.parse(rawVal);
      } catch (e) {
        console.error('[editor_weka] Error parsing JSON');
        console.error(e);
      }
    }

    return WekaValue.fromDoc(doc);
  }
}
