<?php
/*
 * This file is part of Totara LMS
 *
 * Copyright (C) 2016 onwards Totara Learning Solutions LTD
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author  Joby Harding <joby.harding@totaralms.com>
 * @author  Petr Skoda <petr.skoda@totaralms.com>
 * @package totara_core
 */

/* Developer documentation is in /pix/flex_icons.php file. */

$translations = array(
    'totara_core|bookings' => 'calendar',
    'totara_core|comment-point-blue' => 'caret-left-info',
    'totara_core|comment-point-blue-rtl' => 'caret-right-info',
    'totara_core|comment-point-grey' => 'caret-right-disabled',
    'totara_core|comment-point-grey-rtl' => 'caret-left-disabled',
    'totara_core|i/bullet_delete' => 'times-danger',
    'totara_core|i/completion-rpl-n' => 'square-o',
    'totara_core|i/completion-rpl-y' => 'check-square-o',
    'totara_core|i/delete_grey' => 'times-disabled',
    'totara_core|jquery_treeview/folder' => 'folder-open-o',
    'totara_core|jquery_treeview/folder-closed' => 'folder-o',
    'totara_core|loading' => 'spinner-pulse',
    'totara_core|loading_small' => 'spinner-pulse',
    'totara_core|msgicons/blended-add' => 'plus-circle-info',
    'totara_core|msgicons/blended-approve' => 'thumbs-up-success',
    'totara_core|msgicons/blended-complete' => 'check-circle-success',
    'totara_core|msgicons/blended-deadline' => 'alarm',
    'totara_core|msgicons/blended-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/blended-due' => 'alarm-warning',
    'totara_core|msgicons/blended-fail' => 'times-circle-danger',
    'totara_core|msgicons/blended-newcomment' => 'commenting-info',
    'totara_core|msgicons/blended-overdue' => 'alarm-danger',
    'totara_core|msgicons/blended-regular' => 'blended',
    'totara_core|msgicons/blended-remove' => 'times-danger',
    'totara_core|msgicons/blended-request' => 'question-circle-warning',
    'totara_core|msgicons/blended-update' => 'pencil-square-info',
    'totara_core|msgicons/competency-add' => 'plus-circle-info',
    'totara_core|msgicons/competency-approve' => 'thumbs-up-success',
    'totara_core|msgicons/competency-complete' => 'check-circle-success',
    'totara_core|msgicons/competency-deadline' => 'alarm',
    'totara_core|msgicons/competency-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/competency-due' => 'alarm-warning',
    'totara_core|msgicons/competency-fail' => 'times-circle-danger',
    'totara_core|msgicons/competency-newcomment' => 'commenting-info',
    'totara_core|msgicons/competency-overdue' => 'alarm-danger',
    'totara_core|msgicons/competency-regular' => 'competency',
    'totara_core|msgicons/competency-remove' => 'times-danger',
    'totara_core|msgicons/competency-request' => 'question-circle-warning',
    'totara_core|msgicons/competency-update' => 'pencil-square-info',
    'totara_core|msgicons/course-add' => 'plus-circle-info',
    'totara_core|msgicons/course-approve' => 'thumbs-up-success',
    'totara_core|msgicons/course-complete' => 'check-circle-success',
    'totara_core|msgicons/course-deadline' => 'alarm',
    'totara_core|msgicons/course-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/course-due' => 'alarm-warning',
    'totara_core|msgicons/course-fail' => 'times-circle-danger',
    'totara_core|msgicons/course-newcomment' => 'commenting-info',
    'totara_core|msgicons/course-overdue' => 'alarm-danger',
    'totara_core|msgicons/course-regular' => 'cube',
    'totara_core|msgicons/course-remove' => 'times-danger',
    'totara_core|msgicons/course-request' => 'question-circle-warning',
    'totara_core|msgicons/course-update' => 'pencil-square-info',
    'totara_core|msgicons/default' => 'laptop',
    'totara_core|msgicons/elearning-add' => 'plus-circle-info',
    'totara_core|msgicons/elearning-approve' => 'thumbs-up-success',
    'totara_core|msgicons/elearning-complete' => 'check-circle-success',
    'totara_core|msgicons/elearning-deadline' => 'alarm',
    'totara_core|msgicons/elearning-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/elearning-due' => 'alarm-warning',
    'totara_core|msgicons/elearning-fail' => 'times-circle-danger',
    'totara_core|msgicons/elearning-newcomment' => 'commenting-info',
    'totara_core|msgicons/elearning-overdue' => 'alarm-danger',
    'totara_core|msgicons/elearning-regular' => 'laptop',
    'totara_core|msgicons/elearning-remove' => 'times-danger',
    'totara_core|msgicons/elearning-request' => 'question-circle-warning',
    'totara_core|msgicons/elearning-update' => 'pencil-square-info',
    'totara_core|msgicons/evidence-add' => 'plus-circle-info',
    'totara_core|msgicons/evidence-approve' => 'thumbs-up-success',
    'totara_core|msgicons/evidence-complete' => 'check-circle-success',
    'totara_core|msgicons/evidence-deadline' => 'alarm',
    'totara_core|msgicons/evidence-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/evidence-due' => 'alarm-warning',
    'totara_core|msgicons/evidence-fail' => 'times-circle-danger',
    'totara_core|msgicons/evidence-newcomment' => 'commenting-info',
    'totara_core|msgicons/evidence-overdue' => 'alarm-danger',
    'totara_core|msgicons/evidence-regular' => 'paperclip',
    'totara_core|msgicons/evidence-remove' => 'times-danger',
    'totara_core|msgicons/evidence-request' => 'question-circle-warning',
    'totara_core|msgicons/evidence-update' => 'pencil-square-info',
    'totara_core|msgicons/facetoface-add' => 'plus-circle-info',
    'totara_core|msgicons/facetoface-approve' => 'thumbs-up-success',
    'totara_core|msgicons/facetoface-complete' => 'check-circle-success',
    'totara_core|msgicons/facetoface-deadline' => 'alarm',
    'totara_core|msgicons/facetoface-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/facetoface-due' => 'alarm-warning',
    'totara_core|msgicons/facetoface-fail' => 'times-circle-danger',
    'totara_core|msgicons/facetoface-newcomment' => 'commenting-info',
    'totara_core|msgicons/facetoface-overdue' => 'alarm-danger',
    'totara_core|msgicons/facetoface-regular' => 'seminar',
    'totara_core|msgicons/facetoface-remove' => 'times-danger',
    'totara_core|msgicons/facetoface-request' => 'question-circle-warning',
    'totara_core|msgicons/facetoface-update' => 'pencil-square-info',
    'totara_core|msgicons/feedback360-cancel' => 'times-danger',
    'totara_core|msgicons/feedback360-remind' => 'alarm-warning',
    'totara_core|msgicons/feedback360-request' => 'question-circle-warning',
    'totara_core|msgicons/feedback360-update' => 'pencil-square-info',
    'totara_core|msgicons/learningplan-add' => 'plus-circle-info',
    'totara_core|msgicons/learningplan-approve' => 'thumbs-up-success',
    'totara_core|msgicons/learningplan-complete' => 'check-circle-success',
    'totara_core|msgicons/learningplan-deadline' => 'alarm',
    'totara_core|msgicons/learningplan-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/learningplan-due' => 'alarm-warning',
    'totara_core|msgicons/learningplan-fail' => 'times-circle-danger',
    'totara_core|msgicons/learningplan-newcomment' => 'commenting-info',
    'totara_core|msgicons/learningplan-overdue' => 'alarm-danger',
    'totara_core|msgicons/learningplan-regular' => 'briefcase',
    'totara_core|msgicons/learningplan-remove' => 'times-danger',
    'totara_core|msgicons/learningplan-request' => 'question-circle-warning',
    'totara_core|msgicons/learningplan-update' => 'pencil-square-info',
    'totara_core|msgicons/objective-add' => 'plus-circle-info',
    'totara_core|msgicons/objective-approve' => 'thumbs-up-success',
    'totara_core|msgicons/objective-complete' => 'check-circle-success',
    'totara_core|msgicons/objective-deadline' => 'alarm',
    'totara_core|msgicons/objective-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/objective-due' => 'alarm-warning',
    'totara_core|msgicons/objective-fail' => 'times-circle-danger',
    'totara_core|msgicons/objective-newcomment' => 'commenting-info',
    'totara_core|msgicons/objective-overdue' => 'alarm-danger',
    'totara_core|msgicons/objective-regular' => 'objective',
    'totara_core|msgicons/objective-remove' => 'times-danger',
    'totara_core|msgicons/objective-request' => 'question-circle-warning',
    'totara_core|msgicons/objective-update' => 'pencil-square-info',
    'totara_core|msgicons/program-add' => 'plus-circle-info',
    'totara_core|msgicons/program-approve' => 'thumbs-up-success',
    'totara_core|msgicons/program-complete' => 'check-circle-success',
    'totara_core|msgicons/program-deadline' => 'alarm',
    'totara_core|msgicons/program-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/program-due' => 'alarm-warning',
    'totara_core|msgicons/program-fail' => 'times-circle-danger',
    'totara_core|msgicons/program-newcomment' => 'commenting-info',
    'totara_core|msgicons/program-overdue' => 'alarm-danger',
    'totara_core|msgicons/program-regular' => 'cubes',
    'totara_core|msgicons/program-remove' => 'times-danger',
    'totara_core|msgicons/program-request' => 'question-circle-warning',
    'totara_core|msgicons/resource-add' => 'plus-circle-info',
    'totara_core|msgicons/resource-approve' => 'thumbs-up-success',
    'totara_core|msgicons/resource-complete' => 'check-circle-success',
    'totara_core|msgicons/resource-deadline' => 'alarm',
    'totara_core|msgicons/resource-decline' => 'thumbs-down-danger',
    'totara_core|msgicons/resource-due' => 'alarm-warning',
    'totara_core|msgicons/resource-fail' => 'times-circle-danger',
    'totara_core|msgicons/resource-newcomment' => 'commenting-info',
    'totara_core|msgicons/resource-overdue' => 'alarm-danger',
    'totara_core|msgicons/resource-regular' => 'archives-alt',
    'totara_core|msgicons/resource-remove' => 'times-danger',
    'totara_core|msgicons/resource-request' => 'question-circle-warning',
    'totara_core|msgicons/resource-update' => 'pencil-square-info',
    'totara_core|plan' => 'briefcase',
    'totara_core|record' => 'archive-alt',
    'totara_core|t/calendar' => 'calendar',
    'totara_core|t/comments' => 'comment',
    'totara_core|t/comments-none' => 'comment-o',
    'totara_core|t/delete_grey' => 'times-disabled',
    'totara_core|t/file' => 'file-text-o',
    'totara_core|t/minus' => 'minus-square-o',
    'totara_core|t/plus' => 'plus-square-o',
    'totara_core|teammembers' => 'users',
);
